### ISSUE TITLE
[Bug/Question] Incorrect tagging behavior with accented characters

### ISSUE THREAD

**Issue by BobbyESP** [Kyant0/taglib#3]
## Issue Summary:
When attempting to tag audio files using TagLib, specifically when the fields contain words with accent marks, the resulting tags display strange characters or completely different words. This behavior indicates a potential problem with character encoding or handling of special characters within the library.

## Steps to Reproduce:

1. Choose an audio file with metadata fields containing words with accent marks (e.g., á, é, í, ó, ú).
2. Use TagLib to programmatically tag the audio file, setting values for fields with accented characters.
3. Verify the tags applied to the audio file.

## Expected Behavior:
The tags applied to the audio file should accurately reflect the values provided, including any words with accent marks. The text should remain intact and correctly encoded.

## Actual Behavior:
The tags display strange characters or entirely different words instead of the expected text with accent marks. This behavior suggests a potential issue with character encoding or handling within TagLib.

(Sorry for the initial sent info, it was a template I have)

**Comment by BobbyESP** [comment]
For example: "ú" is replaced by "Ãº".

I don't know if I should encode the string in some way for being able to write it correctly

**Comment by Kyant0** [comment]
Which format?

**Comment by BobbyESP** [comment]
> Which format? 

I would say MP3

**Comment by BobbyESP** [comment]
Could you please check by your side if this occurs? I just realized now checking my app that it may be a problem with Jetpack Compose decoding the string bytes...

This is just a note that I leave here since right now I can't test if this is a problem of the lib since I just went to bed haha. Thanks for attending the issue and for the nice library!

**Comment by Kyant0** [comment]
Thanks for reporting! It's fixed. I will publish a new release soon.

**Comment by BobbyESP** [comment]
> Thanks for reporting! It's fixed. I will publish a new release soon.

Thanks!
