### ISSUE TITLE
Large APK size

### ISSUE THREAD

**Issue by sosauce** [Kyant0/taglib#6]
Hello! After using this library my apk went from 3 to 7 mb. Does the library not use minification/shrinkage ?

**Comment by Kyant0** [comment]
The size of the library is shrinked as smaller as possible. The main reason is the native library, almost 1MB for each arch. We can't reduce it, C++ usually produces much codes.

**Comment by sosauce** [comment]
Okay thanks for the info, removing x86 native libraries from my app removes 2mb so its all good
